#!/bin/bash
ENCRYPTED_FILE=$1
if [ "$ENCRYPTED_FILE" == "" ]; then
    echo "usage: $(basename $0) ENCRYPTED_FILE"
    exit 1
fi

sops --decrypt $ENCRYPTED_FILE 2>/dev/null >/dev/null
if [ "$?" == "0" ]; then
    EDITOR=nano sops $ENCRYPTED_FILE
else
    echo -n "Enter SOPS_AGE_KEY: " >&2
    read -s SOPS_AGE_KEY
    echo >&2
    export SOPS_AGE_KEY
    EDITOR=nano sops $ENCRYPTED_FILE
fi
