#!/bin/bash

set -e
set -o pipefail

if [ "$DEBUG" == "1" ]; then
    set -x
else
    echo "Run with env DEBUG=1 to see verbose output."
fi

SCRIPT_DIR=$(dirname $0)

if [ "$2" == "" ]; then
	echo "usage: $(basename $0) DEPLOYMENT_CONFIG MACHINE_NAME"
	exit 1
fi
DEPLOYMENT_CONFIG=$1
MACHINE_NAME=$2

if [ ! -f "$DEPLOYMENT_CONFIG" ]; then
    echo "error: no such file $DEPLOYMENT_CONFIG"
    exit 1
fi
DEPLOYMENT_CONFIG_VALIDATE_JSON=$(cat $DEPLOYMENT_CONFIG | python3 -c "import sys, json; json.load(sys.stdin)" 2>&1 ; true)
if [ "$(echo $DEPLOYMENT_CONFIG_VALIDATE_JSON | grep -c JSONDecodeError)" != "0" ]; then
    echo "error: deployment config is not valid JSON"
    exit 1
fi

# Wait a few seconds in case someone just saw the "Run with DEBUG=1 for verbose" suggestion and want to CTRL-C quickly and re-run with DEBUG=1
sleep 3

SERVER_IP=$($SCRIPT_DIR/lib/create-machine $DEPLOYMENT_CONFIG $MACHINE_NAME)

echo "Starting deploy onto new machine spawned at $SERVER_IP ..."

$SCRIPT_DIR/deploy $DEPLOYMENT_CONFIG $SERVER_IP

echo -e "\n\n\nFinished setting up new machine \"$MACHINE_NAME\" with ip $SERVER_IP\n"

SSHD_PORT=$(cat $DEPLOYMENT_CONFIG | python3 -c "import sys, json; print(json.load(sys.stdin)['sshd_port'])")
if [ "$SSHD_PORT" != "22" ]; then
    echo
    echo "  NOTE: you picked a non-standard sshd port, you might want to add it in .ssh/config"
    echo
fi
