#!/bin/bash

if [ "$DEBUG" == "1" ]; then
    set -x
fi

if [ "$1" != "is-running-on-server" ]; then
    echo -e "\n\n----[ $(basename $0) ]-------------------------------------------"
    if [ "$3" == "" ] || [ "$1" == "--help" ]; then
        echo "usage: $(basename $0) DEPLOYMENT_CONFIG_FILE APP_ID SERVER_IP"
        exit 1
    fi
    CONFIG_FILE=$1
    APP_ID=$2
    SERVER_IP=$3

    DEFAULT_ADMIN_USERNAME=$(cat $CONFIG_FILE | python3 -c "import sys, json; accs = json.load(sys.stdin)['admin_accounts']; print(next((acc for acc in accs if acc['username'] == '"$USERNAME"'), accs[0])['username'])")
    ADMIN_USERNAME=${ADMIN_USERNAME:-$DEFAULT_ADMIN_USERNAME}
    SSHD_PORT=$(cat $CONFIG_FILE | python3 -c "import sys, json; print(json.load(sys.stdin)['sshd_port'])")
    TRAEFIK_REGISTRATION=$(cat $CONFIG_FILE | python3 -c "import sys, json; print('traefik_registration' in json.load(sys.stdin)['apps']['"$APP_ID"'])")
    if [ "$TRAEFIK_REGISTRATION" != "True" ]; then
        echo "Skipping application setup in Traefik."
        exit 0
    fi

    SCRIPT_FILENAME_ON_SERVER=$(ssh -p $SSHD_PORT $ADMIN_USERNAME@$SERVER_IP mktemp)
    scp -qp -P $SSHD_PORT $0 $ADMIN_USERNAME@$SERVER_IP:$SCRIPT_FILENAME_ON_SERVER

    CONFIG_FILENAME_ON_SERVER=$(ssh -p $SSHD_PORT $ADMIN_USERNAME@$SERVER_IP mktemp)
    scp -qp -P $SSHD_PORT $CONFIG_FILE $ADMIN_USERNAME@$SERVER_IP:$CONFIG_FILENAME_ON_SERVER

    LC_ALL=en_US.UTF-8 ssh -q -t $ADMIN_USERNAME@$SERVER_IP -p $SSHD_PORT \
        "$SCRIPT_FILENAME_ON_SERVER is-running-on-server $CONFIG_FILENAME_ON_SERVER $APP_ID ; \
        shred -uz $CONFIG_FILENAME_ON_SERVER ; \
        rm -f $CONFIG_FILENAME_ON_SERVER ; \
        rm -f $SCRIPT_FILENAME_ON_SERVER"
    exit 0
fi

CONFIG_FILE=$2
APP_ID=$3
ADMIN_EMAIL=$(cat $CONFIG_FILE | python3 -c "import sys, json; print(json.load(sys.stdin)['admin_email'])")
APP_DOMAIN_NAME=$(cat $CONFIG_FILE | python3 -c "import sys, json; print(json.load(sys.stdin)['apps']['"$APP_ID"']['domain'])")
APP_WEBSERVER_PORT=$(cat $CONFIG_FILE | python3 -c "import sys, json; print(json.load(sys.stdin)['apps']['"$APP_ID"']['traefik_registration']['port'])")

if [ $EUID -ne 0 ]; then
    ADMIN_PASSWORD=$(cat $CONFIG_FILE | python3 -c "import sys, json; accs = json.load(sys.stdin)['admin_accounts']; print(next((acc for acc in accs if acc['username'] == '"$USERNAME"'), accs[0])['password'])")
    echo $ADMIN_PASSWORD | sudo -S "$0" "$@"
    exit 0
fi
echo ; echo

sudo tee /etc/traefik/conf.d/${APP_ID}.toml >/dev/null <<EOF_MARKER
[frontends]
  [frontends.${APP_ID}_frontend]
    entryPoints = ["http", "https"]
    backend = "${APP_ID}_backend"
    passHostHeader = true

    [frontends.${APP_ID}_frontend.routes.default]
      rule = "Host:${APP_DOMAIN_NAME}"

[backends]
  [backends.${APP_ID}-backend]
    [backends.${APP_ID}-backend.servers]
      [backends.${APP_ID}-backend.servers.server0]
        url = "http://127.0.0.1:${APP_WEBSERVER_PORT}"

    [backends.${APP_ID}-backend.loadBalancer]
      method = "drr"
      [backends.${APP_ID}-backend.loadBalancer.stickiness]
        cookieName = "sticky-session"

[[acme.domains]]
   main = "${APP_DOMAIN_NAME}"
   sans = []
EOF_MARKER
