#!/bin/bash

if [ "$DEBUG" == "1" ]; then
    set -x
fi

if [ "$1" != "is-running-on-server" ]; then
    echo -e "\n\n----[ $(basename $0) ]------------------------------------"
    CONFIG_FILE=$1
    APP_ID=$2
    SERVER_IP=$3
    if [ "$3" == "" ] || [ "$1" == "--help" ]; then
        echo "usage: $(basename $0) DEPLOYMENT_CONFIG_FILE APP_ID SERVER_IP"
        exit 1
    fi

    DEFAULT_ADMIN_USERNAME=$(cat $CONFIG_FILE | python3 -c "import sys, json; accs = json.load(sys.stdin)['admin_accounts']; print(next((acc for acc in accs if acc['username'] == '"$USERNAME"'), accs[0])['username'])")
    ADMIN_USERNAME=${ADMIN_USERNAME:-$DEFAULT_ADMIN_USERNAME}
    SSHD_PORT=$(cat $CONFIG_FILE | python3 -c "import sys, json; print(json.load(sys.stdin)['sshd_port'])")

    SCRIPT_FILENAME_ON_SERVER=$(ssh -p $SSHD_PORT $ADMIN_USERNAME@$SERVER_IP mktemp)
    scp -qp -P $SSHD_PORT $0 $ADMIN_USERNAME@$SERVER_IP:$SCRIPT_FILENAME_ON_SERVER

    CONFIG_FILENAME_ON_SERVER=$(ssh -p $SSHD_PORT $ADMIN_USERNAME@$SERVER_IP mktemp)
    scp -qp -P $SSHD_PORT $CONFIG_FILE $ADMIN_USERNAME@$SERVER_IP:$CONFIG_FILENAME_ON_SERVER

    PUBKEY_FILENAMES=$(cat $CONFIG_FILE | python3 -c "import sys, json; print(' '.join(json.load(sys.stdin)['apps']['"$APP_ID"'].get('public_key_filenames', [])))")
    if [ "$PUBKEY_FILENAMES" == "" ]; then
        PUBKEY_FILENAMES=$HOME/.ssh/id_rsa.pub
    fi
    CONCATENATED_PUBKEYS_FILENAME_LOCAL=$(mktemp)
    (cd $(dirname $CONFIG_FILE) ; cat $PUBKEY_FILENAMES) > $CONCATENATED_PUBKEYS_FILENAME_LOCAL
    PUBKEYS_FILENAME_ON_SERVER=$(ssh -p $SSHD_PORT $ADMIN_USERNAME@$SERVER_IP mktemp)
    scp -qp -P $SSHD_PORT $CONCATENATED_PUBKEYS_FILENAME_LOCAL $ADMIN_USERNAME@$SERVER_IP:$PUBKEYS_FILENAME_ON_SERVER

    LC_ALL=en_US.UTF-8 ssh -q -t $ADMIN_USERNAME@$SERVER_IP -p $SSHD_PORT \
        "$SCRIPT_FILENAME_ON_SERVER is-running-on-server $CONFIG_FILENAME_ON_SERVER $APP_ID $PUBKEYS_FILENAME_ON_SERVER ; \
        shred -uz $CONFIG_FILENAME_ON_SERVER ; \
        rm -f $CONFIG_FILENAME_ON_SERVER ; \
        rm -f $SCRIPT_FILENAME_ON_SERVER ; \
        rm -f $PUBKEYS_FILENAME_ON_SERVER"

    rm -f $CONCATENATED_PUBKEYS_FILENAME_LOCAL
    exit 0
fi

CONFIG_FILE=$2
APP_ID=$3
UPLOADED_CONCATENATED_PUBKEYS_FILENAME=$4
APP_EXEC=$(cat $CONFIG_FILE | python3 -c "import sys, json; print(json.load(sys.stdin)['apps']['"$APP_ID"']['exec'])")
APP_WORKING_DIRECTORY=$(cat $CONFIG_FILE | python3 -c "import sys, json; print(json.load(sys.stdin)['apps']['"$APP_ID"']['working_directory'])")
APP_DESCRIPTION=$(cat $CONFIG_FILE | python3 -c "import sys, json; print(json.load(sys.stdin)['apps']['"$APP_ID"']['description'])")
APP_ROOTLESS_RESTART=$(cat $CONFIG_FILE | python3 -c "import sys, json; print(json.load(sys.stdin)['apps']['"$APP_ID"'].get('rootless_restart', False))")
APP_ROOTLESS_STOP=$(cat $CONFIG_FILE | python3 -c "import sys, json; print(json.load(sys.stdin)['apps']['"$APP_ID"'].get('rootless_stop', False))")

if [ $EUID -ne 0 ]; then
    ADMIN_PASSWORD=$(cat $CONFIG_FILE | python3 -c "import sys, json; accs = json.load(sys.stdin)['admin_accounts']; print(next((acc for acc in accs if acc['username'] == '"$USERNAME"'), accs[0])['password'])")
    echo $ADMIN_PASSWORD | sudo -S "$0" "$@"
    exit 0
fi
echo ; echo

if [ "$(id $APP_ID 2>/dev/null)" == "" ]; then
    adduser --gecos '' --disabled-password $APP_ID
fi

mkdir -p $APP_WORKING_DIRECTORY
chown $APP_ID:$APP_ID $APP_WORKING_DIRECTORY
chmod 700 $APP_WORKING_DIRECTORY

tee /etc/systemd/system/$APP_ID.service >/dev/null <<EOF_MARKER
[Unit]
Description=$APP_DESCRIPTION
After=network.target

[Service]
Type=simple
User=$APP_ID
WorkingDirectory=$APP_WORKING_DIRECTORY
ExecStart=$APP_EXEC
Restart=always

[Install]
WantedBy=multi-user.target
EOF_MARKER
chmod 644 /etc/systemd/system/$APP_ID.service

if [ "$APP_ROOTLESS_RESTART" == "True" ]; then
    echo "%$APP_ID ALL=(ALL) NOPASSWD: /bin/systemctl restart $APP_ID" | EDITOR=tee visudo -f /etc/sudoers.d/$APP_ID-rootless-restart
fi
if [ "$APP_ROOTLESS_STOP" == "True" ]; then
    echo "%$APP_ID ALL=(ALL) NOPASSWD: /bin/systemctl stop $APP_ID" | EDITOR=tee visudo -f /etc/sudoers.d/$APP_ID-rootless-stop
fi

systemctl daemon-reload
systemctl enable $APP_ID.service
systemctl start $APP_ID.service

mkdir -p /home/$APP_ID/.ssh
chown $APP_ID:$APP_ID /home/$APP_ID/.ssh
chmod 700 /home/$APP_ID/.ssh
if [ ! -e "/home/$APP_ID/.ssh/authorized_keys" ]; then
    touch /home/$APP_ID/.ssh/authorized_keys
fi

cat $UPLOADED_CONCATENATED_PUBKEYS_FILENAME >> /home/$APP_ID/.ssh/authorized_keys
cat /home/$APP_ID/.ssh/authorized_keys | sort | uniq > /home/$APP_ID/.ssh/authorized_keys.uniq
mv /home/$APP_ID/.ssh/authorized_keys.uniq /home/$APP_ID/.ssh/authorized_keys

chown $APP_ID:$APP_ID /home/$APP_ID/.ssh/authorized_keys
chmod 600 /home/$APP_ID/.ssh/authorized_keys
